### ISSUE TITLE
Compile error with library.properties

### ISSUE THREAD

**Issue by crashmaxx** [TDoust/M2_12VIO#2]
The "Revisions" line of the library.properties file seems to be formatted wrong. I could not get it to compile until I changed the line to:
`Revisions=Added optional support to work in unison with M2RET ADC DMA & M2I/O`

**Comment by TDoust** [comment]
Thanks for pointing this out.
Corrected now in repository
Minor over site & disappointed that Visual studio did not complain when i was testing
