### ISSUE TITLE
In M2IO.Setpin_12VIO(X,ON) X is not Pin number, but channel number

### ISSUE THREAD

**Issue by dme8a8** [TDoust/M2_12VIO#4]
In M2IO.Setpin_12VIO(X,ON) X is not Pin number, but channel number. That should be documented somewhere!

Also M2IO.Setpin_12VIO(1, ON, SOURCE, PWM_PIN, 1000, 5); gives a measured duty cycle of 8%, so the accuracy could maybe be improved! :-)

Otherwise nice library!!

**Comment by TDoust** [comment]
X refers to one of the M2 GPIO output pins 1-6
so M2IO.Setpin_12VIO(1,ON) set GPIO output 1 On

**Comment by dme8a8** [comment]
Should be documented on the main page! Took me ages of reading the src to find that out
